const BAD_REQUEST = 400;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const HTTPERROR = 409;
const DEFAULT = 500;
const SUCCESS = 200;

module.exports = {
  NOT_FOUND,
  HTTPERROR,
  BAD_REQUEST,
  FORBIDDEN,
  DEFAULT,
  SUCCESS,
};
